Channel Groups Page
GridProtectionAlliance/SystemCenter pull request #120
Opened 2023-07-18 17:43 UTC by Phoenix1128

Add Channel Groups page and functionality to System Center.

2023-07-19 14:06 UTC, clackner-gpa commented on Source/Applications/SystemCenter/AppDebug.config
> +      <add name="NodeID" value="0E3293AE-A19D-458C-8E04-D9032E2386D3" description="Unique Node ID" encrypted="false" />
```suggestion
      <add name="NodeID" value="00000000-0000-0000-0000-000000000000" description="Unique Node ID" encrypted="false" />
```

2023-07-19 14:07 UTC, clackner-gpa commented on Source/Applications/SystemCenter/AppDebug.config
> +      <add name="ConnectionString" value="Data Source=VMTenantDB; Initial Catalog=TVAopenXDA; Integrated Security=SSPI" description="Defines the connection to the openXDA database." encrypted="false"
```suggestion
      <add name="ConnectionString" value="Data Source=localhost; Initial Catalog=openXDA; Integrated Security=SSPI" description="Defines the connection to the openXDA database." encrypted="false" />
```

2023-07-19 14:10 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
> +                CollumnList={SearchFields.ValueListGroup as Search.IField<SystemCenter.Types.ChannelGroup>[]}
`SearchFields.ValueListGroup` is wrong since this is not a `ValueListGroup` you can just copy the actual Field over

2023-07-19 14:11 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
> +                defaultCollumn={DefaultSearchField.ValueListGroup as Search.IField<SystemCenter.Types.ChannelGroup>}
`DefaultSearchField.ValueListGroup` is wrong since this is not a `ValueListGroup` you can just copy the actual Field over

2023-07-19 14:12 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
> +                GetEnum={(setOptions, field) => {
I am not sure we really need to get enums... this is for Filters, but we don't have any enum based filters here....

2023-07-19 14:15 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
> +                SetFilter={(flds) => setSearch(flds)}
```suggestion
                SetFilter={(flds) => dispatch(ChannelGroupSlice.DBSearch({ filter: flds }));}
```
then you  can switch `search` to come from the Slice

2023-07-19 14:16 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
> +                            setSortField(d.colKey as any)
```suggestion
                            dispatch(ChannelGroupSlice.DBSearch({ sortField: d.colKey, ascending: true }))
```

2023-07-19 14:16 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
> +                            setAscending(!d.ascending)
```suggestion
                            dispatch(ChannelGroupSlice.DBSearch({ ascending: !ascending}))
```

2023-07-19 14:17 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroup.tsx
> +        }
```suggestion
```

2023-07-19 14:18 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroup.tsx
> +    }, [dispatch, channelGroupStatus]);
```suggestion
    }, [channelGroupStatus]);
```

2023-07-19 14:19 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupForm.tsx
> +//  CompanyForm.tsx - Gbtc
```suggestion
//  ChannelGroupForm.tsx - Gbtc
```

2023-07-19 14:22 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupInfo.tsx
You need to add better Error explanation and handling.
e.g. If `Name.length > 200` the Form will turn red but there is no indication here that that is a problem and it will attempt to save.
Add Tooltips and validation similar to other pages...

2023-07-19 14:24 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupItemForm.tsx
> +    React.useEffect(() => {
Split these into sepperate uesEffects. We don't need to fire everything every time. React takes care of it.

2023-07-19 18:36 UTC, Phoenix1128 commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupInfo.tsx
Not sure where you're seeing that there's no indication of a problem. Everywhere I looked, if `Name.length > 200` the text would be appear that says Name needs to be less than 200 characters. I have added validation for updating the name of a group though.

2023-07-25 13:47 UTC, clackner-gpa requested changes

2023-07-25 13:47 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupInfo.tsx
in `ChannelGroupForm.tsx` you check for `Name.length > 200` which does turn the field red.
However in `ChannelGroupInfo` you use `ChannelGroupForm` but the update button does not disable and no `Tooltip` is shown if `Name.length < 200` so the user can still click update even if there is an error. Usually we would disable the button and show a tooltip with an X and a description of the error. Check some of the other pages for that

2023-08-01 14:22 UTC, clackner-gpa commented
TSZ does not build since [5d00283](https://github.com/GridProtectionAlliance/SystemCenter/pull/120/commits/5d00283d26ffd7d099b700387ab215d496e42478)

2023-08-01 16:21 UTC, gcsantos-gpa approved these changes

2023-08-10 15:16 UTC, merged