Addl fields demo fixes
GridProtectionAlliance/SystemCenter pull request #234
Opened 2024-01-10 20:41 UTC by gcsantos-gpa

2024-01-10 20:45 UTC, clackner-gpa requested changes
Since `_` and spaces are now treated the same we may want to adjust Line 120 of `AdditionalFieldForm.tsx` to include `replace('_',' ')` or something along those lines to avoid confusion

Or a;lternatively just add an error case if the Field includes `_` at all....

2024-01-10 20:49 UTC, gcsantos-gpa commented
> Since `_` and spaces are now treated the same we may want to adjust Line 120 of `AdditionalFieldForm.tsx` to include `replace('_',' ')` or something along those lines to avoid confusion
> 
> Or a;lternatively just add an error case if the Field includes `_` at all....

Maybe the solution it to add this rule to the check on name uniqueness? I think perserving the ability to make fields either "field_name" or "field name" is important due to how old data could be either.

2024-01-10 21:12 UTC, clackner-gpa commented
Sounds like adding `.replace('_',' ')` on both sides of the `=` should do it then. that way `field_name` and `field name` are considered equal and will throw the error in the UI

2024-01-11 19:25 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AdditionalFields/AdditionalFieldForm.tsx
>              w.push(`A key field already exists for this External Database.`);
```suggestion
            w.push(`A key field already exists for this External Table.`);
```

2024-01-11 19:26 UTC, clackner-gpa approved these changes

2024-01-12 19:09 UTC, merged