issue_SC-26
GridProtectionAlliance/SystemCenter pull request #251
Opened 2024-01-30 19:43 UTC by arianalaur3n

Implements changes to the tables on the Device Issues Page, so that they are complete, up to date, and sort accurately.

2024-01-30 19:47 UTC, elwills approved these changes

2024-02-08 13:58 UTC, clackner-gpa requested changes

2024-02-08 13:58 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/MiMDIssuesPage.tsx
>      }, [props.Meter]);
is there a reason we don't have `sortfield` and `ascending` in the dependencies instead of using the sepperate Effect for sorting?

2024-02-08 13:58 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/Reason.tsx
> +    }
```suggestion
    if (props.Text == '')  return  'N/A'
```

2024-02-08 13:58 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/OpenXDAIssuesPage.tsx
> +        handle.done(d => setData(JSON.parse(d.toString())))
I am assuming the `JSON.parse` is necessary because `d` is a `string`? If that is the case Tying for `handle` should be `JQuery.jqXHR<string>`

2024-02-08 18:22 UTC, gcsantos-gpa requested changes
I agree with Chirstoph's feedback. As a thought though, having a separate use effect for sorting could be good for avoiding unnecessary server calls, but either way works.

2024-02-10 00:20 UTC, clackner-gpa commented
>  could be good for avoiding unnecessary server calls
You are not wrong there, but I don't think this is the place to address that unless it is really needed here.
If the server calls a re a concern we should update `GenericSlice` to sort client side everywhere.
That does bring up another point tho we should develop a NonSlice collection of these functions in Gemstone Especially for common Calls it would be nice to use something like `DailyStatisticsController.Sort(field, asc)`  but that should also go into `gpa-gemstone` if anywhere

2024-05-17 14:08 UTC, gcsantos-gpa commented
Taking over this pr. Since this went up, the generic controllers have been made. Implemented those. We will need a gemstone update in SC before this gets merged in. I recalled Christoph mentioning he would do that, but if not I can include that here.

2024-05-17 14:09 UTC, gcsantos-gpa approved these changes

2024-06-04 12:52 UTC, clackner-gpa requested changes
It is "outdated" because the table is only supposed to show the TOP 50 (?) records by `LastSuccessfulFileProcessed`
That's regardless of the `sortKey` selected by the user in the Table

Because of that the Controller needs to sort by `LastSuccessfulFileProcessed` and the client needs to do the sorting by Table `sortKey` 

otherwhise you get records you don't want (TOP 50 applied across the wrong order)

2024-06-07 19:31 UTC, clackner-gpa approved these changes

2024-06-07 20:06 UTC, merged