Fix for asset key unique checking on meter add asset button
GridProtectionAlliance/SystemCenter pull request #44
Opened 2022-12-21 19:04 UTC by gcsantos-gpa

https://support.gridprotectionalliance.org/tickets/1064

2023-01-16 17:01 UTC, clackner-gpa requested changes

2023-02-21 14:48 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
> +                                        <AssetAttributes.AssetAttributeFields Asset={activeAsset} NewEdit={newEdit} AssetTypes={assetTypes} AllAssets={allAssets}
It is used to populate the select but that select is hidden here, so that's not an issue.

2023-03-03 16:28 UTC, clackner-gpa approved these changes

2023-03-03 16:29 UTC, merged

2023-03-03 16:29 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
> +                                        <AssetAttributes.AssetAttributeFields Asset={activeAsset} NewEdit={newEdit} AssetTypes={assetTypes} AllAssets={allAssets}
We'll keep that on the list of things when we get around to it