SC-171 Fixed NMW Search box styling
GridProtectionAlliance/SystemCenter pull request #462
Opened 2024-08-05 16:06 UTC by Tenacs

…odal is closed

2024-08-06 18:43 UTC, clackner-gpa requested changes

2024-08-06 18:43 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/AssetPage.tsx
> +                                <select multiple style={{ height: '80%', width: '100%' }} onChange={(evt) => {
use `flex` for these. Otherwhsie they depend on the height of the `Input` which may be changing

2024-09-16 15:16 UTC, danielduggin2 commented
Double scroll bars below search bar.

2024-09-30 19:06 UTC, clackner-gpa approved these changes

2024-09-30 19:06 UTC, elwills approved these changes

2024-09-30 19:57 UTC, merged