SC-193 Value Lists Sorting
GridProtectionAlliance/SystemCenter pull request #487
Opened 2024-08-16 19:14 UTC by KulinduC

Relies on OpenXDA changes: https://github.com/GridProtectionAlliance/openXDA/pull/335 and Gemstone changes: https://github.com/GridProtectionAlliance/gpa-gemstone/pull/307

2024-08-16 21:03 UTC, KulinduC commented
![image](https://github.com/user-attachments/assets/e5bcc30e-2554-46fb-99a5-a6f88935c9b2)
![image](https://github.com/user-attachments/assets/0cbefc07-7b40-45e8-982c-5943639d2371)
![image](https://github.com/user-attachments/assets/15f1dcfe-9450-4403-9c8e-a8ecb8f34d3f)

2024-10-14 17:12 UTC, gcsantos-gpa requested changes
I'm not sure I'm seeing the controller for ValueListGroupView. Also, since the view is a child of the non-view, would it not be possible to combine slices via the controller syntax modelcontroller<T, U>

2024-10-14 17:45 UTC, gcsantos-gpa requested changes

2024-10-14 17:45 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
>                          Field={'Items'}
```suggestion
                        Field={'ItemCount'}
```
Change field to reflect custom view

2024-10-14 17:59 UTC, gcsantos-gpa approved these changes

2024-10-14 18:01 UTC, clackner-gpa approved these changes

2024-10-14 18:09 UTC, merged