SC-194 Channel Groups Sorting
GridProtectionAlliance/SystemCenter pull request #488
Opened 2024-08-16 19:16 UTC by KulinduC

Relies on OpenXDA changes: https://github.com/GridProtectionAlliance/openXDA/pull/336 and Gemstone changes: https://github.com/GridProtectionAlliance/gpa-gemstone/pull/306

2024-08-16 21:09 UTC, KulinduC commented
![image](https://github.com/user-attachments/assets/cb5d688d-2ee9-44cd-a185-acc5c2030907)
![image](https://github.com/user-attachments/assets/63761b88-84b9-403e-8d68-a2d48b35033a)
![image](https://github.com/user-attachments/assets/503707c5-cc1a-4375-b1d1-d7880e3dc9c9)

2024-10-14 18:33 UTC, gcsantos-gpa requested changes

2024-10-14 18:33 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
Searchbar should be dispatching ChannelGroupViewSlice not the ChannelGroupSlice

2024-10-14 18:33 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
> +        ChannelGroupView: ChannelGroupViewSlice.Reducer
```suggestion
        ChannelGroupView: ChannelGroupViewSlice.Reducer,
```

2024-10-14 18:33 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
>                          Key={'Items'}
```suggestion
                        Key={'ItemCount'}
```
Arrow for sort indication is based on key not field, so key must also be ItemCount

2024-10-14 18:49 UTC, gcsantos-gpa approved these changes

2024-10-15 23:32 UTC, merged