Updated Installer and Added DOCKER
GridProtectionAlliance/SystemCenter pull request #490
Opened 2024-08-16 23:48 UTC by clackner-gpa

Added DOCKERFILE and included various fixes to run Installer from Console

2024-08-29 15:01 UTC, StephenCWills requested changes

2024-09-06 13:49 UTC, clackner-gpa commented on Source/Tests/UserInterface/ApplicationCategoryTest.cs
> +        driver.FindElement(By.Id("password")).SendKeys("7h1515457r0ngP455w0rd");
Good Point. Can we change this to Environmental Variables maybe?

2024-09-06 16:14 UTC, StephenCWills commented on Source/Tests/UserInterface/ApplicationCategoryTest.cs
> +        driver.FindElement(By.Id("password")).SendKeys("7h1515457r0ngP455w0rd");
Sounds like a plan. Per our discussion, we'll be merging this and then making a new PR. Also, this admin account will be removed from the demo system.

2024-09-06 16:14 UTC, StephenCWills approved these changes

2024-09-06 18:21 UTC, merged