Updated To GenericByPage
GridProtectionAlliance/SystemCenter pull request #549
Opened 2024-11-20 15:03 UTC by collins-self

Changed relevant pages to GenericByPage component

2024-12-03 19:40 UTC, clackner-gpa requested changes

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
> +        };
Should be a Controller call.
Unless you call this in the `useEffect` cleanup won't do anything and should be removed

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DB/DBCleanup.tsx
> +        };
should be a controller call.
Cleanup not needed

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DB/DBCleanup.tsx
> +        };
see above

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DB/DBCleanup.tsx
> +        };
see above

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
> +        })
should be a controller call

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
> +        };
not needed unless you call that in `useEffect`

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalDB.tsx
> +        };
should be a controller call
should not need cleanup

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalTable.tsx
> +//  Copyright � 2019, Grid Protection Alliance.  All Rights Reserved.
I think this has something to do with your VS code settings. See if you can fix that to use the correct character set

2024-12-03 19:40 UTC, clackner-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalTable.tsx
> +        };
Should be a controller call
should not need cleanup

2025-01-15 20:07 UTC, gcsantos-gpa requested changes
The comments I left apply to a lot of places, please fix them wherever you are able.

2025-01-15 20:07 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/ByMagDurCurve.tsx
> +        })
Unless there is something non-standard about this call, can we use the GenericController class to achieve this? That way, if we ever have to change this function we don't have to change it in a bunch of individual places. You do this in more places that just here, can all of them be changed?

2025-01-15 20:07 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
> +    }
This should be replaced by generic controller, similar to above, but just FYI:

In general, we DON'T want to use cleanup functions like this in this kind of function. Imagine for some reason the server is slower than a user, and a user adds two groups quickly before the server can respond. If this cleanup function were to be executed (which wouldn't be the case here since we never do anything with it where we call this function) the JS would cancel the first call, causing the first group to never be added. Usually, we use cleanup functions for server calls that have no use if another one is made (i.e. calls to search the database for some UI component).

2025-01-16 13:11 UTC, collins-self commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
> +    return ( // TODO: Search
It was mistakenly left in

2025-01-16 13:13 UTC, collins-self commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/ByMATLABAnalytic.tsx
> +//  Copyright � 2023, Grid Protection Alliance.  All Rights Reserved.
fix

2025-01-22 14:45 UTC, gcsantos-gpa requested changes

2025-01-22 14:45 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
> +        <GenericByPage<OpenXDA.Types.EventType>
Search bar here doesn't work.

2025-01-22 14:45 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx
> +        <GenericByPage<OpenXDA.Types.RemoteXDAInstance>
If you add and delete an instance, it doesn't go away until refresh.

2025-01-22 14:45 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx
> +    function addOperation() {
These calls look like standard model controller calls, can we use the controller object here like in other places?

2025-01-23 15:40 UTC, collins-self commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx
> +        <GenericByPage<OpenXDA.Types.RemoteXDAInstance>
This bug wasn't totally replicable which is strange, but I made a change to make it more consistent with the ByPages which handle delete functions similarly. In most recent commit.

2025-01-24 13:58 UTC, collins-self commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
> +        <GenericByPage<OpenXDA.Types.EventType>
Fixed with https://github.com/GridProtectionAlliance/openXDA/pull/411

2025-01-24 14:44 UTC, collins-self commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx
> +    function addOperation() {
updated

2025-01-24 18:03 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
> -    function patchConnection(connection: OpenXDA.Types.RemoteXDAInstance): void {
is this no longer required?

2025-01-24 18:05 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx
> +        <GenericByPage<OpenXDA.Types.RemoteXDAInstance>
More consistent in what way? Does this solve the issue?

2025-01-24 18:05 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
> +        window.location.href = homePath + 'index.cshtml?name=RemoteXDAInstanceMain';
As per other conversation, does this resolve the issue?

2025-01-24 18:09 UTC, gcsantos-gpa commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx
> +        <GenericByPage<OpenXDA.Types.RemoteXDAInstance>
Consistent in what way?

2025-01-24 19:42 UTC, collins-self commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
> -    function patchConnection(connection: OpenXDA.Types.RemoteXDAInstance): void {
It seems to never be used anywhere

2025-01-24 19:54 UTC, collins-self commented on Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
> +        window.location.href = homePath + 'index.cshtml?name=RemoteXDAInstanceMain';
Yes I used the Customer page for reference and this was the only difference I could see. With this change it seems to remove the problem

2025-01-24 21:01 UTC, gcsantos-gpa approved these changes

2025-01-27 14:16 UTC, gcsantos-gpa approved these changes

2025-01-27 18:15 UTC, clackner-gpa approved these changes

2025-01-27 18:15 UTC, merged